setwd("/Users/zhengmingsong/Google Drive/R/EDA")
temp <- tempfile(fileext=".zip")
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip" , method = 'curl', destfil = temp )
dateDownloaded = date()
data <- read.table(unz(temp, "household_power_consumption.txt"),,sep=";",header = T)
# data = read.table("data.txt",sep=";",header = T)
unlink(temp)
dates = paste(data[,1],data[,2])
dts = strptime(dates,"%d/%m/%Y %H:%M:%S")
ldt = strptime("2007-02-01", "%Y-%m-%d")
udt = strptime("2007-02-02", "%Y-%m-%d")
sub = data[(as.Date(dts) == as.Date(ldt) | as.Date(dts) == as.Date(udt)),]
subdates = dts[(as.Date(dts) == as.Date(ldt) | as.Date(dts) == as.Date(udt))]
png(filename = "plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(subdates,as.numeric(as.character(sub$Global_active_power)),type = 'l',xlab = "")
plot(subdates,as.numeric(as.character(sub$Voltage)),type = 'l',xlab = "datetime",ylab = "Voltage")
plot(subdates,as.numeric(as.character(sub$Sub_metering_1)),type = 'l',xlab = "",ylab = "Energy sub metering")
lines(subdates,as.numeric(as.character(sub$Sub_metering_2)), col = "red")
lines(subdates,as.numeric(as.character(sub$Sub_metering_3)),col = "blue")
legend("topright", lty = c(1,1,1), c("Sub_metering_1","Sub_metering_2","Sub_metering_1"),col=c("black","red","blue"))
plot(subdates,as.numeric(as.character(sub$Global_reactive_power)),type = 'l',xlab = "datetime",ylab = "Global_reactive_power")
par(mfrow=c(1,1))
dev.off()
